name: Stretcher
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.29.0
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 12.0
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": arm64
    DEVELOPMENT_TEAM: 349WFX4WJR
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.1
targets:
  MessagesExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "12.0"
    info:
      path: MessagesExtension/Info.plist
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "1"
    sources:
      - path: MessagesExtension
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - framework: Messages.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jwitapps.StretchMe.MessagesExtension

  Stretcher:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    info:
      path: Stretcher/Info.plist
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "1"
    sources:
      - path: Stretcher
    dependencies:
      - target: MessagesExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jwitapps.StretchMe

schemes:
  Release:
    build:
      targets:
        Stretcher: all
    run:
      config: Release
    archive:
      config: Release
