name: Textend
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 10.29.0
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 12.0
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": arm64
    DEVELOPMENT_TEAM: 349WFX4WJR
    CURRENT_PROJECT_VERSION: 1.1
    MARKETING_VERSION: 1.1
targets:
  MessagesExtension:
    type: app-extension.messages
    platform: iOS
    deploymentTarget: "12.0"
    info:
      path: MessagesExtension/Info.plist
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "1.1"
        CFBundleDisplayName: Textend
        MSMessagesExtensionStoreIconName: Messages Icon
        NSExtension:
          NSExtensionAttributes: {}
          NSExtensionMainStoryboard: MainInterface
          NSExtensionPointIdentifier: com.apple.message-payload-provider
    sources:
      - path: MessagesExtension
    dependencies:
      - package: Firebase
        product: FirebaseAnalytics
      - framework: Messages.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jwitapps.textend.MessagesExtension
        ASSETCATALOG_COMPILER_APPICON_NAME: Messages Icon

  Textend:
    type: application.messages
    platform: iOS
    deploymentTarget: "12.0"
    info:
      path: Textend/Info.plist
      properties:
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "1.1"
    sources:
      - path: Textend
        excludes:
          - AppDelegate.swift
    dependencies:
      - target: MessagesExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jwitapps.textend

schemes:
  Textend:
    build:
      targets:
        Textend: all
    run:
      config: Debug
    archive:
      config: Release
  TextendMessages:
    build:
      targets:
        MessagesExtension: all
        Textend: all
    run:
      config: Debug
      executable: MessagesExtension
    profile:
      config: Release
      executable: Textend
    archive:
      config: Release
