//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by Developer on 1/23/17.
//  Copyright © 2017 JwitApps. All rights reserved.
//

import UIKit
import Messages

import FirebaseCore
import FirebaseAnalytics

class MainBackgroundView: UIView {
    override func draw(_ rect: CGRect) {
        DesignsStyleKit.drawMainScreenBackground(frame: rect, resizing: .stretch)
    }
}

class InsertImageBackgroundView: UIView {
    override func draw(_ rect: CGRect) {
        DesignsStyleKit.drawInsertImageBackground(frame: rect, resizing: .stretch)
    }
}

class MessagesViewController: MSMessagesAppViewController, FirebaseConfigurable {
    
    var stretchController: StretchViewController?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if FirebaseApp.app() == nil {
            configureFirebase()
        }
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        Analytics.logEvent("MessageSent", parameters: nil)
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }
    
    @IBAction func startPressed(sender: Any) {
        let controller = storyboard!.instantiateViewController(withIdentifier: "StretchViewController") as! StretchViewController
        stretchController = controller
        controller.messageSender = self
        presentStretch(controller)
        
        requestPresentationStyle(.expanded)
        
        Analytics.logEvent("StartPressed", parameters: nil)
    }
    
    func dismissStretchController() {
        if let controller = stretchController {
            dismissStretch(controller)
        }
        stretchController = nil
    }

    private func presentStretch(_ controller: UIViewController) {
        children.forEach { child in
            child.willMove(toParent: nil)
            child.view.removeFromSuperview()
            child.removeFromParent()
        }

        addChild(controller)
        controller.view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(controller.view)

        NSLayoutConstraint.activate([
            controller.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            controller.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            controller.view.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            controller.view.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
        ])

        controller.didMove(toParent: self)
    }

    private func dismissStretch(_ controller: UIViewController) {
        guard controller.parent != nil else { return }
        controller.willMove(toParent: nil)
        controller.view.removeFromSuperview()
        controller.removeFromParent()
    }
}


public protocol FirebaseConfigurable: class {
    var servicesFileName: String { get }
    
    func configureFirebase()
}

public extension FirebaseConfigurable {
    internal var bundle: Bundle {
        return Bundle(for: type(of: self) as AnyClass)
    }
    
    internal var servicesFileName: String {
        return bundle.infoDictionary!["Google Services File"] as! String
    }
    
    public func configureFirebase() {
        guard FirebaseApp.app() == nil else { return }
        guard let optionsPath = bundle.path(forResource: servicesFileName, ofType: "plist"),
              let options = FirebaseOptions(contentsOfFile: optionsPath) else {
            return
        }
        
        FirebaseApp.configure(options: options)
    }
}
